### ISSUE TITLE
issue when remote host is accessed via locally mapped port

### ISSUE THREAD

**Issue by blair-anson** [journeyapps/mongo-oplog-backup#14]
Hi I have a mongo db instance running on a remote server. To access it I've setup port forwarding over ssh. So I simply run `mongo --port 15111` to connect to it.
I have replicaSet configured on the instance and the oplog does have entries in it

```
rs0:PRIMARY> rs.printReplicationInfo()
configured oplog size:   1024MB
log length start to end: 3292secs (0.91hrs)
oplog first event time:  Mon Aug 14 2017 09:29:39 GMT+0900 (JST)
oplog last event time:   Mon Aug 14 2017 10:24:31 GMT+0900 (JST)
now:                     Mon Aug 14 2017 10:24:38 GMT+0900 (JST)
```

however when I try to run a backup I receive the following error. Any suggestions on how to resolve it?...

```
$ mongo-oplog-backup backup --v --port 15111 --dir backup
I, [2017-08-14T01:27:25.884748 #31712]  INFO -- : Performing full backup
D, [2017-08-14T01:27:25.884863 #31712] DEBUG -- : >>> mongo --host localhost --port 15111 --quiet --norc admin /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/oplog-last-timestamp.js
D, [2017-08-14T01:27:26.856995 #31712] DEBUG -- : {}
/var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:129:in `backup_full': Cannot backup with empty oplog (RuntimeError)
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:186:in `block in perform'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:43:in `block in lock'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:37:in `open'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:37:in `lock'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/lib/mongo_oplog_backup/backup.rb:184:in `perform'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/bin/mongo-oplog-backup:55:in `block (3 levels) in <top (required)>'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /var/lib/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
	from /var/lib/gems/2.3.0/gems/mongo-oplog-backup-0.0.12/bin/mongo-oplog-backup:6:in `<top (required)>'
	from /usr/local/bin/mongo-oplog-backup:23:in `load'
	from /usr/local/bin/mongo-oplog-backup:23:in `<main>'
```

**Comment by blair-anson** [comment]
Wrong port  :-(
