### ISSUE TITLE
getting error while back-upping with --oplog option 

### ISSUE THREAD

**Issue by hbakhtiyor** [journeyapps/mongo-oplog-backup#5]
command with options

``` sh
/data/mongodb$ mongo-oplog-backup backup --port 27018 --dir /data/mongodb/backup --oplog
```

exception

```
/var/lib/gems/1.9.1/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:162:in `perform': Unknown backup position - cannot perform oplog backup. (RuntimeError)
    from /var/lib/gems/1.9.1/gems/mongo-oplog-backup-0.0.9/bin/mongo-oplog-backup:47:in `block (3 levels) in <top (required)>'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `call'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
    from /var/lib/gems/1.9.1/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
    from /var/lib/gems/1.9.1/gems/mongo-oplog-backup-0.0.9/bin/mongo-oplog-backup:6:in `<top (required)>'
    from /usr/local/bin/mongo-oplog-backup:23:in `load'
    from /usr/local/bin/mongo-oplog-backup:23:in `<main>'
```

```
~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
~$ gem --version
1.8.23
~$ mongo --version
MongoDB shell version: 2.6.12
~$ uname -a
Linux ub 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hbakhtiyor** [comment]
@rkistner any ideas?

**Comment by hbakhtiyor** [comment]
resolved the issue, i re-run `mongod` with `--replSet=rs0` option

but appear another "errors" without any meaningful messages

```
I, [2016-09-07T08:26:58.375969 #25443]  INFO -- : Performing full backup
D, [2016-09-07T08:26:58.376150 #25443] DEBUG -- : >>> mongo --host localhost --port 27018 --quiet --norc /var/lib/gems/1.9.1/gems/mongo-oplog-backup-0.0.9/oplog-last-timestamp.js
D, [2016-09-07T08:26:58.444351 #25443] DEBUG -- : {"position":{"t":1473260789,"i":1}}
D, [2016-09-07T08:26:58.450277 #25443] DEBUG -- : >>> mongodump --host localhost --port 27018 --out /data/mongodb/backup/backup-1473260789:1/dump
E, [2016-09-07T08:26:58.485699 #25443] ERROR -- : 2016-09-07T08:26:58.485-0700	writing first-demo-service.Collection1 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection1.bson
E, [2016-09-07T08:26:58.485826 #25443] ERROR -- : 2016-09-07T08:26:58.485-0700	writing first-demo-service.Collection2 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection2.bson
E, [2016-09-07T08:26:58.487035 #25443] ERROR -- : 2016-09-07T08:26:58.485-0700	writing first-demo-service.Collection3 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection3.bson
E, [2016-09-07T08:26:58.487100 #25443] ERROR -- : 2016-09-07T08:26:58.486-0700	writing first-demo-service.Collection4 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection4.bson
E, [2016-09-07T08:26:59.451104 #25443] ERROR -- : 2016-09-07T08:26:59.450-0700	done dumping first-demo-service.Collection4 (155463 documents)
E, [2016-09-07T08:26:59.454545 #25443] ERROR -- : 2016-09-07T08:26:59.454-0700	writing first-demo-service.Collection5 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection5.bson
E, [2016-09-07T08:26:59.464501 #25443] ERROR -- : 2016-09-07T08:26:59.463-0700	done dumping first-demo-service.Collection5 (1237 documents)
E, [2016-09-07T08:26:59.464620 #25443] ERROR -- : 2016-09-07T08:26:59.464-0700	writing first-demo-service.Collection6 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection6.bson
E, [2016-09-07T08:26:59.468146 #25443] ERROR -- : 2016-09-07T08:26:59.468-0700	done dumping first-demo-service.Collection6 (387 documents)
E, [2016-09-07T08:26:59.469327 #25443] ERROR -- : 2016-09-07T08:26:59.468-0700	writing second-demo-service.Collection7 to /data/mongodb/backup/backup-1473260789:1/dump/second-demo-service/Collection7.bson
E, [2016-09-07T08:26:59.471588 #25443] ERROR -- : 2016-09-07T08:26:59.471-0700	done dumping second-demo-service.Collection7 (268 documents)
E, [2016-09-07T08:26:59.472759 #25443] ERROR -- : 2016-09-07T08:26:59.471-0700	writing first-demo-service.Collection8 to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Collection8.bson
E, [2016-09-07T08:26:59.473944 #25443] ERROR -- : 2016-09-07T08:26:59.473-0700	done dumping first-demo-service.Collection8 (157 documents)
E, [2016-09-07T08:26:59.474013 #25443] ERROR -- : 2016-09-07T08:26:59.473-0700	writing first-demo-service.Category to /data/mongodb/backup/backup-1473260789:1/dump/first-demo-service/Category.bson
E, [2016-09-07T08:26:59.475182 #25443] ERROR -- : 2016-09-07T08:26:59.474-0700	done dumping first-demo-service.Category (9 documents)
E, [2016-09-07T08:27:01.520912 #25443] ERROR -- : 2016-09-07T08:27:01.517-0700	[####....................]        first-demo-service.Collection1  447106/2166362  (20.6%)
E, [2016-09-07T08:27:01.521023 #25443] ERROR -- : 2016-09-07T08:27:01.517-0700	[######..................]      first-demo-service.Collection2  303998/1081081  (28.1%)
E, [2016-09-07T08:27:01.521064 #25443] ERROR -- : 2016-09-07T08:27:01.517-0700	[##########..............]  first-demo-service.Collection3  453972/1058613  (42.9%)
E, [2016-09-07T08:27:01.521112 #25443] ERROR -- : 2016-09-07T08:27:01.517-0700	
E, [2016-09-07T08:27:04.638188 #25443] ERROR -- : 2016-09-07T08:27:04.637-0700	[#####...................]        first-demo-service.Collection1  456447/2166362  (21.1%)
E, [2016-09-07T08:27:04.638304 #25443] ERROR -- : 2016-09-07T08:27:04.637-0700	[######..................]      first-demo-service.Collection2  309643/1081081  (28.6%)
E, [2016-09-07T08:27:04.638347 #25443] ERROR -- : 2016-09-07T08:27:04.637-0700	[##########..............]  first-demo-service.Collection3  462642/1058613  (43.7%)
E, [2016-09-07T08:27:04.638389 #25443] ERROR -- : 2016-09-07T08:27:04.637-0700	
E, [2016-09-07T08:27:07.520868 #25443] ERROR -- : 2016-09-07T08:27:07.517-0700	[#####...................]        first-demo-service.Collection1  463807/2166362  (21.4%)
E, [2016-09-07T08:27:07.520983 #25443] ERROR -- : 2016-09-07T08:27:07.517-0700	[######..................]      first-demo-service.Collection2  313087/1081081  (29.0%)
E, [2016-09-07T08:27:07.521024 #25443] ERROR -- : 2016-09-07T08:27:07.517-0700	[##########..............]  first-demo-service.Collection3  471296/1058613  (44.5%)
E, [2016-09-07T08:27:07.521065 #25443] ERROR -- : 2016-09-07T08:27:07.517-0700	
E, [2016-09-07T08:27:10.485803 #25443] ERROR -- : 2016-09-07T08:27:10.485-0700	[###########.............]        first-demo-service.Collection1   999093/2166362  (46.1%)
E, [2016-09-07T08:27:10.485941 #25443] ERROR -- : 2016-09-07T08:27:10.485-0700	[############............]      first-demo-service.Collection2   572907/1081081  (53.0%)
E, [2016-09-07T08:27:10.486000 #25443] ERROR -- : 2016-09-07T08:27:10.485-0700	[######################..]  first-demo-service.Collection3  1008021/1058613  (95.2%)
E, [2016-09-07T08:27:10.486104 #25443] ERROR -- : 2016-09-07T08:27:10.485-0700	
E, [2016-09-07T08:27:10.784703 #25443] ERROR -- : 2016-09-07T08:27:10.784-0700	[########################]  first-demo-service.Collection3  1058613/1058613  (100.0%)
E, [2016-09-07T08:27:10.784811 #25443] ERROR -- : 2016-09-07T08:27:10.784-0700	done dumping first-demo-service.Collection3 (1058613 documents)
E, [2016-09-07T08:27:13.486490 #25443] ERROR -- : 2016-09-07T08:27:13.485-0700	[#################.......]    first-demo-service.Collection1  1576997/2166362  (72.8%)
E, [2016-09-07T08:27:13.486583 #25443] ERROR -- : 2016-09-07T08:27:13.485-0700	[####################....]  first-demo-service.Collection2   935284/1081081  (86.5%)
E, [2016-09-07T08:27:13.486642 #25443] ERROR -- : 2016-09-07T08:27:13.485-0700	
E, [2016-09-07T08:27:14.631457 #25443] ERROR -- : 2016-09-07T08:27:14.631-0700	[########################]  first-demo-service.Collection2  1081081/1081081  (100.0%)
E, [2016-09-07T08:27:14.631550 #25443] ERROR -- : 2016-09-07T08:27:14.631-0700	done dumping first-demo-service.Collection2 (1081081 documents)
E, [2016-09-07T08:27:16.486283 #25443] ERROR -- : 2016-09-07T08:27:16.486-0700	[######################..]  first-demo-service.Collection1  2039854/2166362  (94.2%)
E, [2016-09-07T08:27:17.547117 #25443] ERROR -- : 2016-09-07T08:27:17.546-0700	[########################]  first-demo-service.Collection1  2166362/2166362  (100.0%)
E, [2016-09-07T08:27:17.547320 #25443] ERROR -- : 2016-09-07T08:27:17.547-0700	done dumping first-demo-service.Collection1 (2166362 documents)
I, [2016-09-07T08:27:17.555010 #25443]  INFO -- : Performed full backup
I, [2016-09-07T08:27:17.555356 #25443]  INFO -- : Performing incremental oplog backup
D, [2016-09-07T08:27:17.555909 #25443] DEBUG -- : >>> mongodump --host localhost --port 27018 --out /data/mongodb/backup/tmp-dump --db local --collection oplog.rs --query \{ts\ :\ \{\ \$gte\ :\ \{\ \$timestamp\ :\ \{\ t\ :\ 1473260789,\ i\ :\ 1\ \}\ \}\ \}\}
E, [2016-09-07T08:27:17.575747 #25443] ERROR -- : 2016-09-07T08:27:17.575-0700	writing local.oplog.rs to /data/mongodb/backup/tmp-dump/local/oplog.rs.bson
E, [2016-09-07T08:27:17.577325 #25443] ERROR -- : 2016-09-07T08:27:17.577-0700	done dumping local.oplog.rs (1 document)
D, [2016-09-07T08:27:17.580254 #25443] DEBUG -- : Checking timestamps...
I, [2016-09-07T08:27:17.581154 #25443]  INFO -- : Nothing new to backup

```

**Comment by rkistner** [comment]
I agree the error message for the first issue is not clear. Will see if we can improve it.

The ERROR messages in the log are not actually errors - just the "stderr" output from the mongodump command. Will change the log output to make it less confusing.

**Comment by hbakhtiyor** [comment]
but if no errors, why `mongodump` pushing to standard error stream?

**Comment by rkistner** [comment]
That's fairly standard practice for debugging output.

**Comment by rkistner** [comment]
This project is not being maintained anymore - closing all issues.
