### ISSUE TITLE
Cannot figure out backing up of replicaSet, used to work fine on standalone

### ISSUE THREAD

**Issue by virtuman** [journeyapps/mongo-oplog-backup#8]
We used mongo-oplog-backup for quite some time now and it used to work perfectly well on a single-server setup. Since we added a couple of servers and converted to replicaSet - it doesn't seem to be able to work with incremental backups. Is it something that we're not doing right, or is it just not supposed to work with replicaSets, i wasn't able to find any reference to replicasets in the project itself

Here's the message that we get:

_/usr/bin/mongo-oplog-backup backup --dir /data_slow/backups/mongodb --full_

```
I, [2016-09-23T20:09:24.331181 #6993]  INFO -- : Performing full backup
D, [2016-09-23T20:09:24.331299 #6993] DEBUG -- : >>> mongo --host localhost --port 27017 --quiet --norc /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/oplog-last-timestamp.js
D, [2016-09-23T20:09:24.396316 #6993] DEBUG -- : {"position":{"$timestamp":{"t":1474661364,"i":4}}}
D, [2016-09-23T20:09:24.401215 #6993] DEBUG -- : >>> mongodump --host localhost --port 27017 --out /data_slow/backups/mongodb/backup-:/dump
E, [2016-09-23T20:09:24.491961 #6993] ERROR -- : 2016-09-23T20:09:24.490+0000   writing admin.system.users to
E, [2016-09-23T20:09:24.493193 #6993] ERROR -- : 2016-09-23T20:09:24.492+0000   done dumping admin.system.users (1 document)
E, [2016-09-23T20:09:24.493260 #6993] ERROR -- : 2016-09-23T20:09:24.492+0000   writing admin.system.version to
E, [2016-09-23T20:09:24.494443 #6993] ERROR -- : 2016-09-23T20:09:24.493+0000   done dumping admin.system.version (1 document)
.....
.....
.....  some output truncated
.....
.....
I, [2016-09-23T20:11:18.433723 #6993]  INFO -- : Performed full backup
I, [2016-09-23T20:11:18.433940 #6993]  INFO -- : Performing incremental oplog backup
D, [2016-09-23T20:11:18.434287 #6993] DEBUG -- : >>> mongodump --host localhost --port 27017 --out /data_slow/backups/mongodb/tmp-dump --db local --collection oplog.rs --query \{ts\ :\ \{\ \$gte\ :\ \{\ \$timestamp\ :\ \{\ t\ :\ ,\ i\ :\ \ \}\ \}\ \}\}
E, [2016-09-23T20:11:18.455923 #6993] ERROR -- : 2016-09-23T20:11:18.455+0000   Failed: error parsing query as json: invalid character ',' looking for beginning of value
/usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/command.rb:105:in `raise!': Command failed with exit code 1 (RuntimeError)
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/command.rb:99:in `run'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/command.rb:21:in `execute'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/config.rb:64:in `exec'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/config.rb:68:in `mongodump'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:56:in `backup_oplog'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:165:in `block in perform'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:43:in `block in lock'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:37:in `open'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:37:in `lock'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:164:in `perform'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/lib/mongo_oplog_backup/backup.rb:182:in `perform'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/bin/mongo-oplog-backup:47:in `block (3 levels) in <top (required)>'
    from /usr/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
    from /usr/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
    from /usr/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
    from /usr/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
    from /usr/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
    from /usr/lib/ruby/gems/2.2.0/gems/mongo-oplog-backup-0.0.9/bin/mongo-oplog-backup:6:in `<top (required)>'
    from /usr/bin/mongo-oplog-backup:23:in `load'
    from /usr/bin/mongo-oplog-backup:23:in `<main>'
```

**Comment by rkistner** [comment]
Will look into this.

**Comment by dhirenrouterabbit** [comment]
receiving similar error +1

**Comment by amardeokar23** [comment]
Currently [oplog-last-timestamp.js](https://github.com/journeyapps/mongo-oplog-backup/blob/master/oplog-last-timestamp.js) returns output as 

> {"position":{"$timestamp":{"t":1502115172,"i":1}}}

We write this output in state.json file which will then used for incremental backup. BSON::Timestamp.from_json($result['position']) function is used to parse the timestamp value stored in this file which is expecting input in the form of this

> {"t":1502115172,"i":1}

But getting this

> {"$timestamp":{"t":1502115172,"i":1}}

@see [backup.rb](https://github.com/journeyapps/mongo-oplog-backup/blob/master/lib/mongo_oplog_backup/backup.rb) file. So needs to update output generated by [oplog-last-timestamp.js](https://github.com/journeyapps/mongo-oplog-backup/blob/master/oplog-last-timestamp.js) file. 
Add below changes in  [oplog-last-timestamp.js](https://github.com/journeyapps/mongo-oplog-backup/blob/master/oplog-last-timestamp.js) file to get output as

> {"position":{"t":1502115972,"i":1}}


```
@@ -5,7 +5,8 @@
 var last = local['oplog.rs'].find().sort({'$natural': -1}).limit(1)[0];
 var result = {};
 if(last != null) {
-    result = {position: last['ts']};
+    var parsed = JSON.parse(JSON.stringify(last));
+    result = {position: (parsed['ts']['$timestamp'] ? parsed['ts']['$timestamp'] : parsed['ts'])};
 }
 
 print(JSON.stringify(result));
```

Note : I am using mongodb 3.4 .

**Comment by johnshearar** [comment]
Thanks for the detailed debugging @amardeokar23. I believe v0.0.12 should fix this issue.
